# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: master
  hooks:
  - id: shellcheck
- repo: https://github.com/adrienverge/yamllint.git
  rev: master
  hooks:
  - id: yamllint
    files: \.(yaml|yml|yamllint)$
